#!/bin/bash

# MyMovies Search - Quick Launcher
SCRIPT_DIR="/Users/claudioripoli/mymovies_extractor"

cd "$SCRIPT_DIR" || exit 1
# Se non ci sono argomenti, lancia la ricerca interattiva
if [ $# -eq 0 ]; then
    node search_and_extract.js
else
    # Altrimenti usa l'estrattore diretto
    node mymovies_extractor.js "$@"
fi