name: Deploy to Cloud Run (api-server)

on:
  push:
    branches: [ "api-server" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure gcloud
        run: |
          gcloud config set project "${{ vars.GCP_PROJECT_ID }}"
          gcloud config set run/region "${{ vars.GCP_REGION }}"

      - name: Enable APIs
        run: |
          gcloud services enable run.googleapis.com artifactregistry.googleapis.com cloudbuild.googleapis.com

      - name: Create Artifact Registry (if not exists)
        run: |
          gcloud artifacts repositories create containers \
            --repository-format=docker \
            --location="${{ vars.GCP_REGION }}" \
            --description="MyMovies API container images" || true

      - name: Build and push image
        run: |
          IMAGE_REF="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/containers/mymovies-api:${{ github.sha }}"
          echo "Building ${IMAGE_REF}"
          gcloud builds submit --region "${{ vars.GCP_REGION }}" --tag "${IMAGE_REF}" .

      - name: Deploy to Cloud Run
        run: |
          IMAGE_REF="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/containers/mymovies-api:${{ github.sha }}"
          gcloud run deploy mymovies-api \
            --image "${IMAGE_REF}" \
            --platform managed \
            --region "${{ vars.GCP_REGION }}" \
            --allow-unauthenticated \
            --timeout=300 \
            --concurrency=10 \
            --cpu=1 \
            --memory=1Gi \
            --set-env-vars="PUPPETEER_SKIP_DOWNLOAD=true,PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium,NODE_ENV=production"

      - name: Print service URL
        run: |
          echo "Service deployed at:"
          gcloud run services describe mymovies-api --region "${{ vars.GCP_REGION }}" --format='value(status.url)'
